### ISSUE TITLE
[0.14.2] Cannot find module @thumbmarkjs/thumbmarkjs or its corresponding type declarations 

### ISSUE THREAD

**Issue by mmelko** [thumbmarkjs/thumbmarkjs#30]
Hi,  after upgrade to 0.14.2 or 0.14.3 this is thrown. I suspect problem is in the package.json: https://github.com/thumbmarkjs/thumbmarkjs/blob/d3a192e00dba3356e30e199d5fdefee3ed18eca6/package.json#L7, `types` folder was removed by https://github.com/thumbmarkjs/thumbmarkjs/commit/2aadde707a8ef46eab48c843641b12bf55d372a2

**Comment by ilkkapeltola** [comment]
Darnit. Okay, will look into this. I thought I fixed this already.

**Comment by mmelko** [comment]
As you can see I provided a PR :)

**Comment by ilkkapeltola** [comment]
oh my god... what a stoopid mistake :D thanks. Approved

**Comment by ilkkapeltola** [comment]
That's odd. I tried this myself and my IDE was able to find the types even though the package.json was clearly pointing to the wrong path. Anyway, sorry about that 😁
New version is on NPM now with your PR. Much appreciated.

**Comment by mmelko** [comment]
Thanks!
